### ISSUE TITLE
FavoriteMedia - Could not be constructed plugin error

### ISSUE THREAD

**Issue by Skyx-Epic** [Dastan21/BDAddons#97] opened 2022-07-11 21:23 UTC
![image](https://user-images.githubusercontent.com/88912712/178360652-c4643cb5-a101-4653-b517-018967e65a7c.png)

Better Discord crashed then I opened it back up with a warm welcome

**Comment by Dastan21** [comment] 2022-07-11 21:23
Duplicate of #95

**Closed by Dastan21** 2022-07-11 21:23 UTC
Labels: duplicate
