### ISSUE TITLE
"Could not be constructed" (Not same issue)

### ISSUE THREAD

**Issue by Teeeaaa** [Dastan21/BDAddons#101] opened 2022-07-12 09:14 UTC
![image](https://user-images.githubusercontent.com/22724848/178455433-9791125e-2697-43c5-97fa-0057cfa73c40.png)
latest commit doesnt fix either :(

**Comment by Dastan21** [comment] 2022-07-12 09:18
Duplicate of #95.

**Closed by Dastan21** 2022-07-12 09:18 UTC
Labels: duplicate
