### ISSUE TITLE
crashes discord whenever i click on any of the favorited tabs

### ISSUE THREAD

**Issue by bullpoo1234** [Dastan21/BDAddons#35] opened 2021-11-12 23:55 UTC
what should i do?

**Comment by Dastan21** [comment] 2021-11-12 23:57
Duplicate of #33.

From announcement in BetterDiscord server:
"If your Discord is crashing when clicking the GIF or Emoji buttons, disable the Emote Menu in BetterDiscord's settings as well as plugins related to emojis and GIFs. "

**Closed by Dastan21** 2021-11-12 23:57 UTC
