### ISSUE TITLE
[FavoriteMedia]: crash when clicking on channel

### ISSUE THREAD

**Issue by uhokay4** [Dastan21/BDAddons#274] opened 2024-11-03 14:42 UTC
### Discord Build

Canary

### Discord Version

341217

### Plugin Version

v1.10.3

### Steps To Reproduce

have FavoriteMedia installed
go into server/dm/group
it ![image](https://github.com/user-attachments/assets/a1828219-413a-4339-b7b6-07f92a329296)es
shows up screen with reload button, press it
![image](https://github.com/user-attachments/assets/a1828219-413a-4339-b7b6-07f92a329296)es again

### Describe the bug

TypeError: Cannot read properties of undefined (reading 'Messages')
    at MediaFavButton.componentDidMount (FavoriteMedia.plugin.js:1017:141)
    at sX (web.cb121c3769a218014806.js:12:1022191)
    at e (web.cb121c3769a218014806.js:12:1042765)
    at e (web.cb121c3769a218014806.js:12:1042661)
    at web.cb121c3769a218014806.js:12:1042776
    at oB (web.cb121c3769a218014806.js:12:1043288)
    at oR (web.cb121c3769a218014806.js:12:1027896)
    at r6 (web.cb121c3769a218014806.js:12:976420)
    at web.cb121c3769a218014806.js:12:1025232

**Comment by Dastan21** [comment] 2024-11-04 09:46
Caused by ZereLibrary

**Comment by NicholasDip** [comment] 2024-11-06 01:44
> Caused by ZereLibrary

still crashes with ZereLibary Disabled/Removed entirely

**Comment by Dastan21** [comment] 2024-11-16 22:11
Fixed in v1.11.1

**Closed by Dastan21** 2024-11-16 22:11 UTC
Labels: bug, related
