### ISSUE TITLE
[FavoriteMedia]: Failed to compile

### ISSUE THREAD

**Issue by fain6789** [Dastan21/BDAddons#143] opened 2022-11-20 07:23 UTC
### Discord Build

Stable

### Discord Version

Stable 159692 (79ae406)

### Plugin Version

v1.6.2

### Steps To Reproduce

1. Download plugin from https://betterdiscord.app/plugin/FavoriteMedia .
2. Move plugin to C:\Users\User\AppData\Roaming\BetterDiscord\plugins.
3. Issue is showing in Discord.

### Describe the bug

when I download this plugin, Discord show me some issue about "Failed to compile"

### Screenshots

![image](https://user-images.githubusercontent.com/113277295/202890715-7136671f-4c04-47d9-9be3-dee6b81d894b.png)
![image](https://user-images.githubusercontent.com/113277295/202890727-9ffbb11e-2fdf-4326-9f13-3965f69556b2.png)

**Comment by Dastan21** [comment] 2022-11-20 09:06
Duplicate of #141

**Closed by Dastan21** 2022-11-20 09:06 UTC
Labels: duplicate, TBD
