### ISSUE TITLE
[FavoriteMedia]: 

### ISSUE THREAD

**Issue by BENJFxmboy** [Dastan21/BDAddons#135] opened 2022-11-09 14:17 UTC
### Discord Build

Stable

### Discord Version

Stable 157215

### Plugin Version

1.6.2

### Steps To Reproduce

TypeError: Cannot read property 'ComponentDispatch' of undefined
    at eval (betterdiscord://plugins/FavoriteMedia.plugin.js:343:75)
    at eval (betterdiscord://plugins/FavoriteMedia.plugin.js:4592:4)
    at eval (betterdiscord://plugins/FavoriteMedia.plugin.js:4593:3)
    at Object.requireAddon (<anonymous>:4:39192)
    at Object.loadAddon (<anonymous>:4:9163)
    at Object.loadAddon (<anonymous>:4:36864)
    at Object.reloadAddon (<anonymous>:4:10053)
    at AsyncFunction.<anonymous> (<anonymous>:4:7189)

### Describe the bug

failed to compile, tried fixing somthing and it worked but another bug came right after 

### Screenshots

![image](https://user-images.githubusercontent.com/117836250/200851777-ab75407d-9c2f-4527-9819-468ac63e4690.png)

**Comment by Dastan21** [comment] 2022-11-09 14:18
Duplicate of #131

**Closed by Dastan21** 2022-11-09 14:18 UTC
Labels: duplicate
