### ISSUE TITLE
FavoriteMedia - out of box issue

### ISSUE THREAD

**Issue by master3395** [Dastan21/BDAddons#30] opened 2021-11-05 17:42 UTC
When you want to put one gif as a favorite on the right side of the box, The favorite button is outside of the frame.

Stable 103508 (42e6c51)
BetterDiscord 1.2.4
Host 1.0.9003 Windows 10 64-Bit (10.0.22000)

![image](https://user-images.githubusercontent.com/4199669/140554927-9d021fbb-f832-4981-8340-65c94e56f779.png)

**Comment by Dastan21** [comment] 2021-11-05 17:44
You can stretch the tab. Duplicate of #16

**Closed** 2021-11-05 17:46 UTC
Labels: duplicate, question
