### ISSUE TITLE
FavoriteMedia still crashing

### ISSUE THREAD

**Issue by huangdangwibu** [Dastan21/BDAddons#34] opened 2021-11-12 10:42 UTC
still crashing after the third reinstall: https://gyazo.com/7fde8b14695dbc533fe59e18535cac18

**Comment by Dastan21** [comment] 2021-11-12 10:45
Are you on Stable, PTB or Canary ? I just tested on Canary and it crashes

**Comment by Dastan21** [comment] 2021-11-12 10:52
Seems to be caused by Emoji Menu, cannot do much, just disable it (and reload) until it is fixed by BD

**Closed by Dastan21** 2021-11-12 10:52 UTC
