### ISSUE TITLE
FavoriteMedia could not be constructed error

### ISSUE THREAD

**Issue by PicoBeBlamming122** [Dastan21/BDAddons#99] opened 2022-07-12 03:05 UTC
It says that:
`FavoriteMedia: Could not be constructed.
    at Object.initializeAddon (<anonymous>:4:306871)
    at Object.loadAddon (<anonymous>:4:268358)
    at Object.loadAddon (<anonymous>:4:305909)
    at Object.reloadAddon (<anonymous>:4:269069)
    at FSWatcher.<anonymous> (<anonymous>:4:266241)`
I don't know how to fix this, I have the ability to go into the code and try to fix it myself so I keep all my memes, which I have the things I need to do in order to do so but I would need help. But if I have to delete all of my stuff for it I can also do that, please notify me on how to fix this please. Thank you
- Sossis

**Comment by maenDisease** [comment] 2022-07-12 06:42
Please contribute to existing issues rather than creating a separate issue for the same issue.
Duplicate of https://github.com/Dastan21/BDAddons/issues/94 and addressed in commit https://github.com/Dastan21/BDAddons/commit/053c21f07fea721b220a9973382e0b79f5f7f419. Please redownload the plugin from the lastest commit. https://raw.githubusercontent.com/Dastan21/BDAddons/053c21f07fea721b220a9973382e0b79f5f7f419/plugins/FavoriteMedia/FavoriteMedia.plugin.js

**Closed** 2022-07-12 09:19 UTC
