### ISSUE TITLE
[FavoriteMedia]: Could not be compiled. See console for details.

### ISSUE THREAD

**Issue by PancakeFuhrer** [Dastan21/BDAddons#132] opened 2022-10-21 17:39 UTC
### Discord Build

Stable

### Discord Version

Stable 153481

### Plugin Version

1.6.2

### Steps To Reproduce

Everytime I download 

### Describe the bug

ADDON ERRORS

Could not be compiled. See console for details.

TypeError: Cannot read property 'ComponentDispatch' of undefined
    at eval (betterdiscord://plugins/FavoriteMedia.plugin.js:343:75)
    at eval (betterdiscord://plugins/FavoriteMedia.plugin.js:4592:4)
    at eval (betterdiscord://plugins/FavoriteMedia.plugin.js:4593:3)
    at Object.requireAddon (<anonymous>:4:39192)
    at Object.loadAddon (<anonymous>:4:9163)
    at Object.loadAddon (<anonymous>:4:36864)
    at AsyncFunction.<anonymous> (<anonymous>:4:7155)

### Screenshots

![image](https://user-images.githubusercontent.com/116380678/197255936-4ca6f4c1-4caf-428c-a8d7-f91442eacf51.png)

**Comment by Dastan21** [comment] 2022-10-21 17:58
Duplicate of #131

**Closed by Dastan21** 2022-10-21 17:58 UTC
Labels: duplicate
