### ISSUE TITLE
Images seccion bugged 

### ISSUE THREAD

**Issue by TxRichardxT** [Dastan21/BDAddons#107] opened 2022-07-21 01:38 UTC
It was working good this morning but looks like it bugged and appears like this:
![image](https://user-images.githubusercontent.com/94150125/180108731-b371ddfc-8004-42eb-a07d-fc81af691b66.png)

I tried to restart discord and re open the pluggin but it doesnt fix.

I tried re installing pluggin but still not works, also sometimes is starting to stop showing in the bar

**Comment by Dastan21** [comment] 2022-07-21 11:47
Duplicate of #103

**Closed by Dastan21** 2022-07-21 11:47 UTC
Labels: duplicate
