### ISSUE TITLE
[FavoriteMedia]: Media preview cache location?

### ISSUE THREAD

**Issue by Fallen-Feces** [Dastan21/BDAddons#264] opened 2024-07-17 07:36 UTC
### Describe the solution you'd like

Not really sure how else to ask this but where is the local cache database for media preview being stored? I wanna make sure it doesn't annihilate my C: drive (just 2 images and a video made 2MB and I tend to favorite thousands of files this will add up FAST). Would it be possible to configure where it stores things?

**Comment by Dastan21** [comment] 2024-07-17 07:39
There is a panel for local database (btn near the 0)
![image](https://github.com/user-attachments/assets/cbcb5db1-a476-4090-8083-27bc898779a2)

**Comment by DeCat4** [comment] 2024-07-17 11:41
would still be nice to locate the exact location of the cache or be able to configure it in case our c drive can't have the space
any chance you can tell us the location if you won't make a feature to configure the location?

**Comment by Dastan21** [comment] 2024-07-17 11:44
I'm using [IndexedDB](https://javascript.info/indexeddb), so it's internal to the browser, in this case Discord Electron.

**Comment by DeCat4** [comment] 2024-07-17 11:54
oooh alright, also one more question, is it possible to import images just with png,jpeg files from our computer or does it still require discord links? I guess you can take this as a feature request, rn the import button only takes config files, would be nice if it'd be able to take in any files that can be favorited from our pc.

**Comment by Dastan21** [comment] 2024-07-17 11:58
There is an issue for that #232.
The problem is that importing files from our computer means that they have to be uploaded evereytime. Plus there is the limit of 25MB (or more for Nitro).

**Comment by DeCat4** [comment] 2024-07-17 13:14
You could make it so if you upload a file that is too big depending on your nitro you get a warning pop up that stops you from uploading it.

Uploading the file again every time you sent it isn't a problem tbh, discord has plenty of storage and now they seem to wipe out or compress files after the link expires, not sure. As long as the picker isn't laggy or extremelly slow at loading when you have mass amounts of media it's fine.
You could also just make it so after you upload importer media it uses the link to turn it into a regular favorited media and the plugin handles it like usual, idk if discord has a way to forcibly upload images without sending a message but if that's a thing you could do that with media import, turn all of them into links and handle them the same way you do images rn.


I don't really have any experience coding Discord plugins i'm just throwing ideas around based on my limited knowledge with coding, i understand if this is too much or not possible.

**Comment by MahdeenSky** [comment] 2024-07-18 02:15
There was weird bug with local caching when loading, where a memory leak happens, and discord does this.

![Screenshot 2024-07-17 at 10 09 21 PM](https://github.com/user-attachments/assets/80cac4bc-07dd-4d9e-a1a3-90438611988d)

Although it doesn't happen again, i thought it was worth noting.

**Comment by Rexxxyxyxy** [comment] 2024-07-20 20:54
we fr need a fix

**Comment by Rexxxyxyxy** [comment] 2024-07-20 20:58
need to add back refresh button it was easier and saved a lot of trouble anyone know how i can revert it but still make it work

**Comment by Dastan21** [comment] 2024-07-21 13:32
> There was weird bug with local caching when loading, where a memory leak happens, and discord does this.
> 
> ![Screenshot 2024-07-17 at 10 09 21 PM](https://private-user-images.githubusercontent.com/49484385/349758087-80cac4bc-07dd-4d9e-a1a3-90438611988d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1NTExMzcsIm5iZiI6MTcyMTU1MDgzNywicGF0aCI6Ii80OTQ4NDM4NS8zNDk3NTgwODctODBjYWM0YmMtMDdkZC00ZDllLWExYTMtOTA0Mzg2MTE5ODhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDA4MzM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1ZWZjZTY2YjEwYWVjZTI4MjFlZmQ4YmJjYzE1MjYxNjMwNmIwMTIzODNkZDg2NjJmNWY5Mzk2NTBmYjBmZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g0-wZ_FDYbLeznRrZ6kCBuJ6waRCLr6zka6WRtK-jrk)
> 
> Although it doesn't happen again, i thought it was worth noting.

Fixed in 1.10.1 https://github.com/Dastan21/BDAddons/issues/265#issuecomment-2241612801

**Closed** 2024-07-21 13:33 UTC
Labels: feature, question
