### ISSUE TITLE
[Crash] FavoriteMedia

### ISSUE THREAD

**Issue by aahlw** [Dastan21/BDAddons#56] opened 2022-02-05 18:59 UTC
**Issue**
- Discord crash

**Cause**
- FavoriteMedia

**Config**
- OS: macOS 12.1
- Discord Client: Canary
- Discord Version: 113678 (2a9f76c)
- BetterDiscord Versoin: 1.5.0
- Plugin Version: 1.5.6

**Description**
- Sending a favorited image and then editing the message to add another favorited image causes Discord to crash.

**Example**
![ezgif com-gif-maker](https://user-images.githubusercontent.com/62909766/152655054-b81e8fd2-533d-4daf-b6eb-52aebadfa1c5.gif)

**Comment by Dastan21** [comment] 2022-02-05 19:02
Seems to be caused by BetterDiscord, I'm waiting their fix first.

**Comment by Dastan21** [comment] 2022-02-06 08:52
Fixed in v1.5.7.
Note: because I didn't found why it crashes, sending a media while editing a message will not edit the message but just post the link and close the tab.

**Closed by Dastan21** 2022-02-06 08:52 UTC
Labels: bug
