### ISSUE TITLE
[FavoriteMedia]: 

### ISSUE THREAD

**Issue by Ali240-max** [Dastan21/BDAddons#146] opened 2022-11-28 07:05 UTC
### Discord Build

Stable

### Discord Version

160645

### Plugin Version

1.6.2

### Steps To Reproduce

1. Download plugin from https://betterdiscord.app/plugin/FavoriteMedia .
2. Move plugin to C:\Users\User\AppData\Roaming\BetterDiscord\plugins.
3. Issue is showing in Discord.

### Describe the bug

whenever i open discord, it shows the message of failed to compile. 

### Screenshots

![image](https://user-images.githubusercontent.com/76901028/204214721-53731dea-74b7-4c63-934c-804a134ef72b.png)

**Comment by Dastan21** [comment] 2022-11-28 11:54
Duplicate of https://github.com/Dastan21/BDAddons/issues/141

**Closed by Dastan21** 2022-11-28 11:54 UTC
Labels: TBD
