### ISSUE TITLE
FavoriteMedia: Could not be constructed. 

### ISSUE THREAD

**Issue by peebo29** [Dastan21/BDAddons#102] opened 2022-07-12 09:21 UTC
FavoriteMedia: Could not be constructed.
    at Object.initializeAddon (<anonymous>:4:306871)
    at Object.loadAddon (<anonymous>:4:268358)
    at Object.loadAddon (<anonymous>:4:305909)
    at Object.reloadAddon (<anonymous>:4:269069)
    at FSWatcher.<anonymous> (<anonymous>:4:266241)

**Comment by Dastan21** [comment] 2022-07-12 09:35
Duplicate of #95.

**Closed by Dastan21** 2022-07-12 09:35 UTC
Labels: duplicate
